--CONSULTAS
--Consulta: LA CANTIDAD DE ERRORES DE SEVERIDAD "critico" EN EL ÚLTIMO MES

SELECT COUNT(severidad) FROM ERRORES
WHERE severidad = "critico" AND fecha_hora >= ADD_MONTHS(SYSDATE, -1)
GROUP BY severidad
;



-- Consulta: LAS NOTIFICACIONES DE LOS PERFILES QUE SEAN DE EL PAIS 'Colombia' ordenados por fecha

SELECT id, fecha, PERFILES.pais FROM NOTIFICACIONES
JOIN PERFILES ON PERFILES.correo = NOTIFICACIONES.id
WHERE perfiles.pais = 'Colombia'
ORDER BY NOTIFICACIONES.fecha ASC